        const searchResponses = {
    "owners projects": [
        { title: "The Unblocked cat", url: "https://joercat.github.io", description: "Welcome to The Unblocked cat, an ad-free unblocked games website." },
        { title: "Search browser", url: "https://cybertoilet.github.io", description: "Welcome to The Unblocked cat's internet search browser, a free and ad-free search browser." },
        { title: "Meme soundboard", url: "https://cybertoilet.github.io", description: "No description provided :(" },

    ],
    "weather": [
        { title: "Current Weather", url: "https://weather.com", description: "Check the current weather in your area." },
        { title: "Weather Forecast", url: "https://forecast.weather.gov", description: "Get a detailed weather forecast for the coming days." },
        { title: "Severe Weather Alerts", url: "https://www.weatherunderground.com/alerts", description: "Stay informed about severe weather conditions." },
        { title: "Global Weather Maps", url: "https://www.windy.com", description: "Interactive weather maps from around the world." },
        { title: "Climate Data", url: "https://www.ncdc.noaa.gov", description: "Access historical climate data and trends." },
    ],
    "news": [
        { title: "World News", url: "https://news.google.com", description: "Latest news from around the world." },
        { title: "Local News", url: "https://localnews.com", description: "Stay updated with your local news." },
        { title: "Technology News", url: "https://techcrunch.com", description: "Latest updates in technology and startups." },
        { title: "Science News", url: "https://www.sciencedaily.com", description: "Recent discoveries and advancements in science." },
        { title: "Business News", url: "https://www.bloomberg.com", description: "Stay informed about global business and finance." },
    ],
    "recipes": [
        { title: "Quick and Easy Recipes", url: "https://www.allrecipes.com", description: "Find quick and easy recipes for any meal." },
        { title: "Healthy Eating", url: "https://www.eatingwell.com", description: "Discover healthy recipes and nutrition tips." },
        { title: "International Cuisines", url: "https://www.epicurious.com", description: "Explore recipes from around the world." },
        { title: "Vegetarian and Vegan", url: "https://www.vegrecipesofindia.com", description: "Delicious vegetarian and vegan recipe ideas." },
        { title: "Baking and Desserts", url: "https://sallysbakingaddiction.com", description: "Sweet treats and baking recipes for all skill levels." },
    ],
    "entertainment": [
        { title: "Movie Reviews", url: "https://www.rottentomatoes.com", description: "Read reviews and ratings for the latest movies." },
        { title: "TV Show Recommendations", url: "https://www.imdb.com/tv", description: "Discover new TV shows and find ratings." },
        { title: "Streaming Services", url: "https://www.netflix.com", description: "Watch movies and TV shows online." },
        { title: "Celebrity News", url: "https://www.tmz.com", description: "Get the latest celebrity gossip and entertainment news." },
        { title: "Event Tickets", url: "https://www.ticketmaster.com", description: "Find and purchase tickets for live events." },
    ],
    "sports": [
        { title: "Sports News", url: "https://www.espn.com", description: "Get the latest sports news and scores." },
        { title: "Live Scores", url: "https://www.flashscore.com", description: "Real-time scores for various sports." },
        { title: "Fantasy Sports", url: "https://fantasy.espn.com", description: "Play fantasy sports leagues online." },
        { title: "Sports Statistics", url: "https://www.sports-reference.com", description: "Comprehensive sports statistics and history." },
        { title: "Olympic Games", url: "https://olympics.com", description: "Official website of the Olympic Games." },
    ],
    "technology": [
        { title: "Tech News", url: "https://techcrunch.com", description: "Stay updated with the latest in technology." },
        { title: "Gadget Reviews", url: "https://www.theverge.com", description: "Read reviews of the latest gadgets and tech products." },
        { title: "Coding Tutorials", url: "https://www.codecademy.com", description: "Learn to code with interactive tutorials." },
        { title: "Tech Forums", url: "https://forums.tomshardware.com", description: "Discuss technology topics with enthusiasts." },
        { title: "AI News", url: "https://www.artificialintelligence-news.com", description: "Latest news and developments in AI." },
    ],
    "health": [
        { title: "Health Information", url: "https://www.webmd.com", description: "Access reliable health information and resources." },
        { title: "Fitness Trackers", url: "https://www.fitbit.com", description: "Monitor your health and fitness with wearable devices." },
        { title: "Mental Health", url: "https://www.mind.org.uk", description: "Resources and support for mental health issues." },
        { title: "Nutrition Facts", url: "https://nutritiondata.self.com", description: "Detailed nutrition information for various foods." },
        { title: "Medical Symptom Checker", url: "https://symptomchecker.webmd.com", description: "Check your symptoms and find possible causes." },
    ],
    "finance": [
        { title: "Financial News", url: "https://www.bloomberg.com", description: "Stay informed about global finance and markets." },
        { title: "Stock Tracker", url: "https://finance.yahoo.com", description: "Track stocks and manage your portfolio." },
        { title: "Personal Finance", url: "https://www.nerdwallet.com", description: "Tips and tools for managing your personal finances." },
        { title: "Cryptocurrency", url: "https://coinmarketcap.com", description: "Track cryptocurrency prices and market caps." },
        { title: "Investment Education", url: "https://www.investopedia.com", description: "Learn about investing and financial concepts." },
    ],
    "education": [
        { title: "Online Courses", url: "https://www.coursera.org", description: "Explore a wide range of online courses and certifications." },
        { title: "Language Learning", url: "https://www.duolingo.com", description: "Learn new languages for free." },
        { title: "Educational Videos", url: "https://www.khanacademy.org", description: "Free educational videos on various subjects." },
        { title: "Study Resources", url: "https://www.studystack.com", description: "Create and share flashcards and study materials." },
        { title: "Academic Journals", url: "https://www.jstor.org", description: "Access academic journals and research papers." },
    ],
    "travel": [
        { title: "Travel Guides", url: "https://www.lonelyplanet.com", description: "Find travel tips and destination guides." },
        { title: "Flight Booking", url: "https://www.skyscanner.com", description: "Compare and book flights from various airlines." },
        { title: "Hotel Reservations", url: "https://www.booking.com", description: "Book accommodations worldwide." },
        { title: "Travel Reviews", url: "https://www.tripadvisor.com", description: "Read reviews from fellow travelers." },
        { title: "Travel Insurance", url: "https://www.worldnomads.com", description: "Get travel insurance for your trips." },
    ],
    "science": [
        { title: "Scientific Discoveries", url: "https://www.nature.com", description: "Read about the latest scientific research and breakthroughs." },
        { title: "Space Exploration", url: "https://www.nasa.gov", description: "Learn about space missions and discoveries." },
        { title: "Science Experiments", url: "https://www.sciencekids.co.nz", description: "Fun science experiments for kids." },
        { title: "Science Podcasts", url: "https://www.scientificamerican.com/podcasts", description: "Listen to science-related podcasts." },
        { title: "Citizen Science", url: "https://scistarter.org", description: "Participate in real scientific research projects." },
    ],
    "books": [
        { title: "Book Recommendations", url: "https://www.goodreads.com", description: "Discover new books and read reviews." },
        { title: "E-books", url: "https://www.gutenberg.org", description: "Free e-books in the public domain." },
        { title: "Audiobooks", url: "https://www.audible.com", description: "Listen to audiobooks narrated by professionals." },
        { title: "Book Clubs", url: "https://www.bookbrowse.com/bookclubs", description: "Join online book clubs and discussions." },
        { title: "Literary News", url: "https://lithub.com", description: "Stay updated with literary news and culture." },
    ],
    "music": [
        { title: "Music Streaming", url: "https://www.spotify.com", description: "Listen to millions of songs and podcasts." },
        { title: "Music News", url: "https://pitchfork.com", description: "Read music news, reviews, and features." },
        { title: "Concert Tickets", url: "https://www.livenation.com", description: "Find and purchase concert tickets." },
        { title: "Music Theory", url: "https://www.musictheory.net", description: "Learn music theory with interactive lessons." },
        { title: "Lyrics Database", url: "https://genius.com", description: "Find song lyrics and their meanings." },
    ],
    "art": [
        { title: "Virtual Museum Tours", url: "https://artsandculture.google.com", description: "Explore art collections from around the world." },
        { title: "Art History", url: "https://smarthistory.org", description: "Learn about art history and cultural heritage." },
        { title: "Digital Art", url: "https://www.deviantart.com", description: "Discover and share digital art creations." },
        { title: "Art Supplies", url: "https://www.dickblick.com", description: "Shop for art supplies and materials." },
        { title: "Art Tutorials", url: "https://www.artistsnetwork.com", description: "Learn various art techniques and skills." },
    ],
    "fitness": [
        { title: "Workout Plans", url: "https://www.fitnessblender.com", description: "Access free workout videos and fitness programs." },
        { title: "Yoga Classes", url: "https://www.doyogawithme.com", description: "Practice yoga with online classes." },
        { title: "Running Tracker", url: "https://www.strava.com", description: "Track your runs and connect with other runners." },
        { title: "Nutrition Planner", url: "https://www.myfitnesspal.com", description: "Plan and track your meals and nutrition." },
        { title: "Fitness Challenges", url: "https://www.30dayfitnesschallenge.com", description: "Join fitness challenges to stay motivated." },
    ],
    "pets": [
        { title: "Pet Care Tips", url: "https://www.petmd.com", description: "Find information on pet health and care." },
        { title: "Pet Adoption", url: "https://www.petfinder.com", description: "Find pets available for adoption near you." },
        { title: "Pet Supplies", url: "https://www.chewy.com", description: "Shop for pet food, toys, and accessories." },
        { title: "Pet Training", url: "https://www.akc.org/expert-advice/training", description: "Learn how to train your pets effectively." },
        { title: "Pet Insurance", url: "https://www.petinsurance.com", description: "Compare and choose pet insurance plans." },
        { title: "Cats website", url: "https://cats.com", description: "A website for every thing cats." },
    ],
    "gardening": [
        { title: "Gardening Advice", url: "https://www.gardenersworld.com", description: "Get tips and inspiration for your garden." },
        { title: "Plant Identification", url: "https://www.inaturalist.org", description: "Identify plants using a community-driven database." },
        { title: "Seed Catalogs", url: "https://www.burpee.com", description: "Browse and purchase seeds for your garden." },
        { title: "Gardening Tools", url: "https://www.gardeners.com", description: "Shop for gardening tools and equipment." },
        { title: "Composting Guide", url: "https://www.planetnatural.com/composting-101", description: "Learn how to start and maintain a compost pile." },
    ],
    "fashion": [
        { title: "Fashion Trends", url: "https://www.vogue.com", description: "Stay updated with the latest fashion trends." },
        { title: "Online Shopping", url: "https://www.asos.com", description: "Shop for clothing and accessories online." },
        { title: "Fashion Blog", url: "https://www.manrepeller.com", description: "Read fashion blogs and style inspiration." },
        { title: "Sustainable Fashion", url: "https://goodonyou.eco", description: "Discover ethical and sustainable fashion brands." },
        { title: "Fashion History", url: "https://fashionhistory.fitnyc.edu", description: "Explore the history of fashion and costume." },
    ],
    "automotive": [
        { title: "Car Reviews", url: "https://www.caranddriver.com", description: "Read expert reviews on the latest vehicles." },
        { title: "Auto Parts", url: "https://www.rockauto.com", description: "Shop for auto parts and accessories." },
],
    "unblocked games": [
        { title: "The Unblocked cat", url: "https://joercat.github.io", description: "Welcome to The Unblocked cat, an ad-free unblocked games website." },
        { title: "The pizza edition", url: "https://thepizzaedition.github.io", description: "The Pizza Has TONS of experiences to explore! Dive into Retro, Subway, and even Papas Games! The Pizza Edition offers special features, that will not be found anywhere else!" },
        { title: "Chess.com", url: "https://superhardalgebraproblems.com", description: "No description provided :(" },
    { title: "Classic Games", url: "https://classicreload.com", description: "Play classic games from your childhood in your browser." },
    { title: "Unblocked Games 66", url: "https://unblockedgames66.com", description: "A collection of fun unblocked games to play at school." },
    { title: "Cool Math Games", url: "https://www.coolmathgames.com", description: "Play fun math-related games and puzzles for all ages." },
],     
"home improvement": [
        { title: "DIY Projects", url: "https://www.homedepot.com/c/DIY_Projects", description: "Explore DIY projects for your home." },
        { title: "Home Renovation Tips", url: "https://www.bhg.com/home-improvement", description: "Get tips for renovating your home effectively." },
        { title: "Interior Design Ideas", url: "https://www.housebeautiful.com", description: "Discover creative interior design inspirations." },
        { title: "Gardening Ideas", url: "https://www.gardeningknowhow.com", description: "Find gardening ideas and tips for your space." },
        { title: "Home Repair Guides", url: "https://www.repairclinic.com", description: "Get guides on common home repairs." },
    ],
    "parenting": [
        { title: "Parenting Advice", url: "https://www.parents.com", description: "Tips and advice for all stages of parenting." },
        { title: "Kids Activities", url: "https://www.kidsactivitiesblog.com", description: "Fun and engaging activities for kids." },
        { title: "Education Resources", url: "https://www.parenting.com/education", description: "Find educational resources for your child." },
        { title: "Parenting Blogs", url: "https://www.mommyblogs.com", description: "Read personal experiences and advice from parents." },
        { title: "Family Health", url: "https://www.cdc.gov/family/kids", description: "Health information for families and kids." },
    ],
    "cooking": [
        { title: "Meal Planning", url: "https://www.mealime.com", description: "Plan your meals with easy-to-follow recipes." },
        { title: "Cooking Techniques", url: "https://www.cookinglight.com/cooking-techniques", description: "Learn essential cooking techniques." },
        { title: "Seasonal Recipes", url: "https://www.fruitsandveggies.org", description: "Explore recipes featuring seasonal produce." },
        { title: "Kitchen Hacks", url: "https://www.bonappetit.com", description: "Discover kitchen hacks to simplify your cooking." },
        { title: "Food Preservation", url: "https://www.homepreserving.org", description: "Learn about canning and preserving food." },
    ],
    "mental health": [
        { title: "Mental Health Resources", url: "https://www.nami.org", description: "Access resources for mental health support." },
        { title: "Mindfulness Practices", url: "https://www.headspace.com", description: "Explore mindfulness and meditation techniques." },
        { title: "Therapy Options", url: "https://www.betterhelp.com", description: "Find online therapy and counseling services." },
        { title: "Stress Management", url: "https://www.apa.org/topics/stress", description: "Learn how to manage and reduce stress." },
        { title: "Self-Care Tips", url: "https://www.psychologytoday.com/us/basics/self-care", description: "Discover self-care practices for well-being." },
    ],
    "sustainability": [
        { title: "Sustainable Living Tips", url: "https://www.earthday.org", description: "Learn how to live a more sustainable lifestyle." },
        { title: "Eco-Friendly Products", url: "https://www.zerowastehome.com", description: "Discover zero waste and eco-friendly products." },
        { title: "Sustainable Gardening", url: "https://www.permaculture.org", description: "Explore techniques for sustainable gardening." },
        { title: "Renewable Energy", url: "https://www.nrel.gov", description: "Learn about renewable energy sources and options." },
        { title: "Conservation Efforts", url: "https://www.worldwildlife.org", description: "Get involved in global conservation efforts." },
    ],
    "gaming": [
        { title: "Latest Game Releases", url: "https://www.ign.com", description: "Stay updated on the latest video game releases." },
        { title: "Game Reviews", url: "https://www.gamespot.com", description: "Read reviews for the newest games on the market." },
        { title: "Gaming News", url: "https://www.polygon.com", description: "Catch up on the latest news and trends in gaming." },
        { title: "Game Trailers", url: "https://www.youtube.com/games", description: "Watch trailers for upcoming games." },
        { title: "Gaming Communities", url: "https://www.reddit.com/r/gaming", description: "Join discussions in gaming communities." },
    ],
    "cooking tips": [
        { title: "Kitchen Safety Tips", url: "https://www.foodsafety.gov", description: "Learn essential kitchen safety tips." },
        { title: "Healthy Cooking Tips", url: "https://www.eatingwell.com", description: "Explore tips for healthier cooking." },
        { title: "Cooking for One", url: "https://www.onepotdishrecipe.com", description: "Find recipes and tips for cooking for one." },
        { title: "Meal Prep Tips", url: "https://www.mealpreponfleek.com", description: "Master meal prepping with helpful tips." },
        { title: "Cooking Substitutions", url: "https://www.cookinglight.com/cooking-101/cooking-substitutions", description: "Discover common cooking substitutions." },
    ],
    "home organization": [
        { title: "Decluttering Tips", url: "https://www.theminimalists.com", description: "Learn how to declutter your home effectively." },
        { title: "Storage Solutions", url: "https://www.ikea.com/us/en/rooms/storage-solutions/", description: "Find innovative storage solutions for your home." },
        { title: "Organizing Hacks", url: "https://www.apartmenttherapy.com", description: "Explore hacks to organize your living space." },
        { title: "Time Management", url: "https://www.toggl.com/time-management", description: "Learn tips for managing your time effectively." },
        { title: "Cleaning Schedules", url: "https://www.cleanmama.com", description: "Get cleaning schedules to keep your home tidy." },
    ],
    "self-improvement": [
        { title: "Personal Development Books", url: "https://www.goodreads.com", description: "Discover popular personal development books." },
        { title: "Goal Setting Techniques", url: "https://www.mindtools.com", description: "Learn effective goal-setting strategies." },
        { title: "Time Management Skills", url: "https://www.briantracy.com", description: "Improve your time management skills." },
        { title: "Motivational Podcasts", url: "https://www.stitcher.com", description: "Listen to motivational podcasts to inspire you." },
        { title: "Life Coaching", url: "https://www.coaching.com", description: "Find resources and coaches for personal development." },
    ],
    "hobbies": [
        { title: "Crafting Ideas", url: "https://www.craftsy.com", description: "Explore various crafting projects and ideas." },
        { title: "Photography Tips", url: "https://www.photographytalk.com", description: "Learn tips and techniques for better photography." },
        { title: "Model Building", url: "https://www.scalemates.com", description: "Find resources and guides for model building." },
        { title: "Creative Writing", url: "https://www.nanowrimo.org", description: "Participate in writing challenges and workshops." },
        { title: "Gardening as a Hobby", url: "https://www.thegardengate.com", description: "Learn how to start gardening as a hobby." },
    ],
    "mythology": [
        { title: "Greek Mythology", url: "https://www.greekmythology.com", description: "Explore stories and characters from Greek myths." },
        { title: "Norse Mythology", url: "https://www.norsemythologyforfolks.com", description: "Discover the tales of Norse gods and heroes." },
        { title: "Egyptian Mythology", url: "https://www.ancient-egypt-online.com", description: "Learn about the mythology of ancient Egypt." },
        { title: "Mythology Podcasts", url: "https://www.mythologypodcast.com", description: "Listen to engaging discussions about various mythologies." },
        { title: "Mythological Creatures", url: "https://www.monstropedia.org", description: "A comprehensive guide to mythological creatures." },
    ],
    "urban exploration": [
        { title: "Abandoned Places", url: "https://www.abandonedamerica.us", description: "Explore abandoned buildings and urban sites." },
        { title: "Urban Exploration Safety Tips", url: "https://www.urbex.net", description: "Stay safe while exploring urban environments." },
        { title: "Photo Galleries of Urbex", url: "https://www.urbexphotography.com", description: "Stunning photography from urban explorers." },
        { title: "Urbex Communities", url: "https://www.reddit.com/r/urbanexploration", description: "Join the urban exploration community on Reddit." },
        { title: "Urbex Documentary Films", url: "https://www.documentarytube.com", description: "Watch documentaries about urban exploration." },
    ],
    "philosophy": [
        { title: "Introduction to Philosophy", url: "https://www.philosophy.org", description: "Learn the basics of philosophical thought." },
        { title: "Famous Philosophers", url: "https://plato.stanford.edu", description: "Explore the works of renowned philosophers." },
        { title: "Philosophy Podcasts", url: "https://www.philosophytalk.org", description: "Listen to discussions on various philosophical topics." },
        { title: "Philosophical Quotes", url: "https://www.goodreads.com/quotes/tag/philosophy", description: "Find inspiration in famous philosophical quotes." },
        { title: "Ethics and Morality", url: "https://www.iep.utm.edu/ethics", description: "Study the concepts of ethics and morality." },
    ],
    "space science": [
        { title: "NASA Missions", url: "https://www.nasa.gov", description: "Stay updated on NASA's latest missions and research." },
        { title: "Astronomy for Beginners", url: "https://www.astronomy.com", description: "Learn the basics of astronomy and stargazing." },
        { title: "Space Exploration News", url: "https://space.com", description: "Read the latest news about space exploration." },
        { title: "Astrophysics Resources", url: "https://www.astro.umd.edu", description: "Explore resources on astrophysics." },
        { title: "Space Observatories", url: "https://www.esa.int", description: "Learn about various space observatories around the world." },
    ],
    "historical events": [
        { title: "World War II History", url: "https://www.ww2history.com", description: "Learn about significant events from World War II." },
        { title: "Ancient Civilizations", url: "https://www.history.com/topics/ancient-civilizations", description: "Explore ancient civilizations and their legacies." },
        { title: "Cold War Resources", url: "https://www.coldwar.org", description: "Understand the complexities of the Cold War." },
        { title: "Civil Rights Movement", url: "https://www.crmvet.org", description: "Discover the history of the Civil Rights Movement." },
        { title: "Historical Documentaries", url: "https://www.history.com/videos", description: "Watch documentaries about various historical events." },
    ],
    "comics": [
        { title: "Comic Book Reviews", url: "https://www.comicbookresources.com", description: "Read reviews and news about comic books." },
        { title: "Webcomics", url: "https://www.webcomicdirectory.com", description: "Explore a directory of webcomics." },
        { title: "Comic Conventions", url: "https://www.comic-con.org", description: "Find information about upcoming comic conventions." },
        { title: "Graphic Novel Recommendations", url: "https://www.goodreads.com/shelf/show/graphic-novels", description: "Discover popular graphic novels." },
        { title: "Comic Art Tutorials", url: "https://www.skillshare.com/browse/comics", description: "Learn to create comic art through tutorials." },
    ],
    "board games": [
        { title: "Board Game Reviews", url: "https://www.boardgamegeek.com", description: "Find reviews and ratings for board games." },
        { title: "Board Game Strategies", url: "https://www.tabletopgamer.com", description: "Learn strategies for popular board games." },
        { title: "How to Play Board Games", url: "https://www.rainydaygames.com", description: "Get instructions for playing various board games." },
        { title: "Board Game Accessories", url: "https://www.thegamecrafter.com", description: "Shop for board game accessories." },
        { title: "Board Game Communities", url: "https://www.reddit.com/r/boardgames", description: "Join discussions with other board game enthusiasts." },
    ],
    "alternative music": [
        { title: "Indie Music Discoveries", url: "https://www.indieshuffle.com", description: "Find new indie music and artists." },
        { title: "Music Festivals", url: "https://www.musicfestivalwizard.com", description: "Explore upcoming music festivals." },
        { title: "Alternative Music Blogs", url: "https://www.pasteMagazine.com/music", description: "Read blogs and articles on alternative music." },
        { title: "Bandcamp Discoveries", url: "https://bandcamp.com", description: "Support independent artists through Bandcamp." },
        { title: "Music Reviews", url: "https://pitchfork.com", description: "Read reviews on the latest alternative music." },
    ],
    "puzzles": [
        { title: "Sudoku Resources", url: "https://www.sudoku.com", description: "Play and learn Sudoku strategies." },
        { title: "Crossword Puzzles", url: "https://www.nytimes.com/crosswords", description: "Solve daily crossword puzzles." },
        { title: "Logic Puzzles", url: "https://www.brainbashers.com", description: "Challenge yourself with logic puzzles." },
        { title: "Jigsaw Puzzles", url: "https://www.jigsawplanet.com", description: "Create and solve jigsaw puzzles online." },
        { title: "Puzzle Competitions", url: "https://www.worldpuzzle.org", description: "Join competitions for various types of puzzles." },
    ],
        };
