        const searchResponses = {
    "weather": [
        { title: "Current Weather", url: "https://weather.com", description: "Check the current weather in your area." },
        { title: "Weather Forecast", url: "https://forecast.weather.gov", description: "Get a detailed weather forecast for the coming days." },
        { title: "Severe Weather Alerts", url: "https://www.weatherunderground.com/alerts", description: "Stay informed about severe weather conditions." },
        { title: "Global Weather Maps", url: "https://www.windy.com", description: "Interactive weather maps from around the world." },
        { title: "Climate Data", url: "https://www.ncdc.noaa.gov", description: "Access historical climate data and trends." },
    ],
    "news": [
        { title: "World News", url: "https://news.google.com", description: "Latest news from around the world." },
        { title: "Local News", url: "https://localnews.com", description: "Stay updated with your local news." },
        { title: "Technology News", url: "https://techcrunch.com", description: "Latest updates in technology and startups." },
        { title: "Science News", url: "https://www.sciencedaily.com", description: "Recent discoveries and advancements in science." },
        { title: "Business News", url: "https://www.bloomberg.com", description: "Stay informed about global business and finance." },
    ],
    "recipes": [
        { title: "Quick and Easy Recipes", url: "https://www.allrecipes.com", description: "Find quick and easy recipes for any meal." },
        { title: "Healthy Eating", url: "https://www.eatingwell.com", description: "Discover healthy recipes and nutrition tips." },
        { title: "International Cuisines", url: "https://www.epicurious.com", description: "Explore recipes from around the world." },
        { title: "Vegetarian and Vegan", url: "https://www.vegrecipesofindia.com", description: "Delicious vegetarian and vegan recipe ideas." },
        { title: "Baking and Desserts", url: "https://sallysbakingaddiction.com", description: "Sweet treats and baking recipes for all skill levels." },
    ],
    "entertainment": [
        { title: "Movie Reviews", url: "https://www.rottentomatoes.com", description: "Read reviews and ratings for the latest movies." },
        { title: "TV Show Recommendations", url: "https://www.imdb.com/tv", description: "Discover new TV shows and find ratings." },
        { title: "Streaming Services", url: "https://www.netflix.com", description: "Watch movies and TV shows online." },
        { title: "Celebrity News", url: "https://www.tmz.com", description: "Get the latest celebrity gossip and entertainment news." },
        { title: "Event Tickets", url: "https://www.ticketmaster.com", description: "Find and purchase tickets for live events." },
    ],
    "sports": [
        { title: "Sports News", url: "https://www.espn.com", description: "Get the latest sports news and scores." },
        { title: "Live Scores", url: "https://www.flashscore.com", description: "Real-time scores for various sports." },
        { title: "Fantasy Sports", url: "https://fantasy.espn.com", description: "Play fantasy sports leagues online." },
        { title: "Sports Statistics", url: "https://www.sports-reference.com", description: "Comprehensive sports statistics and history." },
        { title: "Olympic Games", url: "https://olympics.com", description: "Official website of the Olympic Games." },
    ],
    "technology": [
        { title: "Tech News", url: "https://techcrunch.com", description: "Stay updated with the latest in technology." },
        { title: "Gadget Reviews", url: "https://www.theverge.com", description: "Read reviews of the latest gadgets and tech products." },
        { title: "Coding Tutorials", url: "https://www.codecademy.com", description: "Learn to code with interactive tutorials." },
        { title: "Tech Forums", url: "https://forums.tomshardware.com", description: "Discuss technology topics with enthusiasts." },
        { title: "AI News", url: "https://www.artificialintelligence-news.com", description: "Latest news and developments in AI." },
    ],
    "health": [
        { title: "Health Information", url: "https://www.webmd.com", description: "Access reliable health information and resources." },
        { title: "Fitness Trackers", url: "https://www.fitbit.com", description: "Monitor your health and fitness with wearable devices." },
        { title: "Mental Health", url: "https://www.mind.org.uk", description: "Resources and support for mental health issues." },
        { title: "Nutrition Facts", url: "https://nutritiondata.self.com", description: "Detailed nutrition information for various foods." },
        { title: "Medical Symptom Checker", url: "https://symptomchecker.webmd.com", description: "Check your symptoms and find possible causes." },
    ],
    "finance": [
        { title: "Financial News", url: "https://www.bloomberg.com", description: "Stay informed about global finance and markets." },
        { title: "Stock Tracker", url: "https://finance.yahoo.com", description: "Track stocks and manage your portfolio." },
        { title: "Personal Finance", url: "https://www.nerdwallet.com", description: "Tips and tools for managing your personal finances." },
        { title: "Cryptocurrency", url: "https://coinmarketcap.com", description: "Track cryptocurrency prices and market caps." },
        { title: "Investment Education", url: "https://www.investopedia.com", description: "Learn about investing and financial concepts." },
    ],
    "education": [
        { title: "Online Courses", url: "https://www.coursera.org", description: "Explore a wide range of online courses and certifications." },
        { title: "Language Learning", url: "https://www.duolingo.com", description: "Learn new languages for free." },
        { title: "Educational Videos", url: "https://www.khanacademy.org", description: "Free educational videos on various subjects." },
        { title: "Study Resources", url: "https://www.studystack.com", description: "Create and share flashcards and study materials." },
        { title: "Academic Journals", url: "https://www.jstor.org", description: "Access academic journals and research papers." },
    ],
    "travel": [
        { title: "Travel Guides", url: "https://www.lonelyplanet.com", description: "Find travel tips and destination guides." },
        { title: "Flight Booking", url: "https://www.skyscanner.com", description: "Compare and book flights from various airlines." },
        { title: "Hotel Reservations", url: "https://www.booking.com", description: "Book accommodations worldwide." },
        { title: "Travel Reviews", url: "https://www.tripadvisor.com", description: "Read reviews from fellow travelers." },
        { title: "Travel Insurance", url: "https://www.worldnomads.com", description: "Get travel insurance for your trips." },
    ],
    "science": [
        { title: "Scientific Discoveries", url: "https://www.nature.com", description: "Read about the latest scientific research and breakthroughs." },
        { title: "Space Exploration", url: "https://www.nasa.gov", description: "Learn about space missions and discoveries." },
        { title: "Science Experiments", url: "https://www.sciencekids.co.nz", description: "Fun science experiments for kids." },
        { title: "Science Podcasts", url: "https://www.scientificamerican.com/podcasts", description: "Listen to science-related podcasts." },
        { title: "Citizen Science", url: "https://scistarter.org", description: "Participate in real scientific research projects." },
    ],
    "books": [
        { title: "Book Recommendations", url: "https://www.goodreads.com", description: "Discover new books and read reviews." },
        { title: "E-books", url: "https://www.gutenberg.org", description: "Free e-books in the public domain." },
        { title: "Audiobooks", url: "https://www.audible.com", description: "Listen to audiobooks narrated by professionals." },
        { title: "Book Clubs", url: "https://www.bookbrowse.com/bookclubs", description: "Join online book clubs and discussions." },
        { title: "Literary News", url: "https://lithub.com", description: "Stay updated with literary news and culture." },
    ],
    "music": [
        { title: "Music Streaming", url: "https://www.spotify.com", description: "Listen to millions of songs and podcasts." },
        { title: "Music News", url: "https://pitchfork.com", description: "Read music news, reviews, and features." },
        { title: "Concert Tickets", url: "https://www.livenation.com", description: "Find and purchase concert tickets." },
        { title: "Music Theory", url: "https://www.musictheory.net", description: "Learn music theory with interactive lessons." },
        { title: "Lyrics Database", url: "https://genius.com", description: "Find song lyrics and their meanings." },
    ],
    "art": [
        { title: "Virtual Museum Tours", url: "https://artsandculture.google.com", description: "Explore art collections from around the world." },
        { title: "Art History", url: "https://smarthistory.org", description: "Learn about art history and cultural heritage." },
        { title: "Digital Art", url: "https://www.deviantart.com", description: "Discover and share digital art creations." },
        { title: "Art Supplies", url: "https://www.dickblick.com", description: "Shop for art supplies and materials." },
        { title: "Art Tutorials", url: "https://www.artistsnetwork.com", description: "Learn various art techniques and skills." },
    ],
    "fitness": [
        { title: "Workout Plans", url: "https://www.fitnessblender.com", description: "Access free workout videos and fitness programs." },
        { title: "Yoga Classes", url: "https://www.doyogawithme.com", description: "Practice yoga with online classes." },
        { title: "Running Tracker", url: "https://www.strava.com", description: "Track your runs and connect with other runners." },
        { title: "Nutrition Planner", url: "https://www.myfitnesspal.com", description: "Plan and track your meals and nutrition." },
        { title: "Fitness Challenges", url: "https://www.30dayfitnesschallenge.com", description: "Join fitness challenges to stay motivated." },
    ],
    "pets": [
        { title: "Pet Care Tips", url: "https://www.petmd.com", description: "Find information on pet health and care." },
        { title: "Pet Adoption", url: "https://www.petfinder.com", description: "Find pets available for adoption near you." },
        { title: "Pet Supplies", url: "https://www.chewy.com", description: "Shop for pet food, toys, and accessories." },
        { title: "Pet Training", url: "https://www.akc.org/expert-advice/training", description: "Learn how to train your pets effectively." },
        { title: "Pet Insurance", url: "https://www.petinsurance.com", description: "Compare and choose pet insurance plans." },
        { title: "Cats website", url: "https://cats.com", description: "A website for every thing cats." },
    ],
    "gardening": [
        { title: "Gardening Advice", url: "https://www.gardenersworld.com", description: "Get tips and inspiration for your garden." },
        { title: "Plant Identification", url: "https://www.inaturalist.org", description: "Identify plants using a community-driven database." },
        { title: "Seed Catalogs", url: "https://www.burpee.com", description: "Browse and purchase seeds for your garden." },
        { title: "Gardening Tools", url: "https://www.gardeners.com", description: "Shop for gardening tools and equipment." },
        { title: "Composting Guide", url: "https://www.planetnatural.com/composting-101", description: "Learn how to start and maintain a compost pile." },
    ],
    "fashion": [
        { title: "Fashion Trends", url: "https://www.vogue.com", description: "Stay updated with the latest fashion trends." },
        { title: "Online Shopping", url: "https://www.asos.com", description: "Shop for clothing and accessories online." },
        { title: "Fashion Blog", url: "https://www.manrepeller.com", description: "Read fashion blogs and style inspiration." },
        { title: "Sustainable Fashion", url: "https://goodonyou.eco", description: "Discover ethical and sustainable fashion brands." },
        { title: "Fashion History", url: "https://fashionhistory.fitnyc.edu", description: "Explore the history of fashion and costume." },
    ],
    "automotive": [
        { title: "Car Reviews", url: "https://www.caranddriver.com", description: "Read expert reviews on the latest vehicles." },
        { title: "Auto Parts", url: "https://www.rockauto.com", description: "Shop for auto parts and accessories." },
]

        };